os: windows
language: shell

before_script:
  - dotnet restore
  - dotnet build -c Release

stages:
  - name: test
    if: type = push AND env(steam) IS present
  - name: deploy
    if: type = push AND fork = false AND env(nuget_key) IS present
    on:
      repo: dragonfruitnetwork/Link
      tags: true

jobs:
  include: 
  - stage: test
    name: "Unit Tests"
    os: linux
    dist: bionic
    language: csharp
    mono: none
    dotnet: 3.1.201
  
    script: dotnet test

  - stage: deploy
    name: "NuGet Beta"
    if: branch = latest
    script:
      - choco install visualstudio2019-workload-netcorebuildtools
      - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
      - dotnet restore
      - dotnet build -c Release
      - powershell -File Nuget.ps1 -Suffix "-beta"

  - name: "NuGet Stable"
    if: branch = master
    stage: deploy
    script:
      - choco install visualstudio2019-workload-netcorebuildtools
      - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
      - dotnet restore
      - dotnet build -c Release
      - powershell -File Nuget.ps1