os: linux
dist: bionic
language: csharp
mono: none
dotnet: 3.1.201

before_script:
  - dotnet restore
  - dotnet build -c Release

stages:
  - name: test
    if: type = push AND env(steam) IS present

jobs:
  include: 
  - stage: test
    name: "Unit Tests"
    script: dotnet test