os: windows
language: shell

before_script:
  - dotnet restore
  - dotnet build -c Release

stages:
  - name: test
    if: env(steam) IS present
  - name: deploy
    if: env(nuget_key) IS present

jobs:
  include: 
  - stage: test
    name: "Unit Tests"
    os: linux
    dist: bionic
    language: csharp
    mono: none
    dotnet: 3.1.201
  
    script: dotnet test

  - stage: deploy
    name: "NuGet Beta"
    if: branch = latest AND type = push AND fork = false
    before_script: 
      - choco install visualstudio2019-workload-netcorebuildtools
      - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
    script:
      - dotnet restore
      - dotnet build -c Release
      - powershell -File Nuget.ps1 -Suffix "-beta"

  - name: "NuGet Stable"
    stage: deploy
    if: tag IS NOT blank AND fork = false
    before_script:
      - choco install visualstudio2019-workload-netcorebuildtools
      - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
    script:
      - dotnet restore
      - dotnet build -c Release
      - powershell -File Nuget.ps1
