name: Beta Release

on:
  push:
    branches:
      - master
    
jobs:
  test:
    
    runs-on: ubuntu-latest
    
    env:
      steam: ${{ secrets.steam }}
  
    steps:
      - name: "Unit Tests"
        uses: ./.github/workflows/codequality.yaml
      
  beta:
    runs-on: windows-latest
    
    env:
      nuget_key: ${{ secrets.nuget_key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Dependencies (Chocolatey)
        run: |
          choco install visualstudio2019-netcorebuildtools
          choco install nuget.commandline
         
      - name: "Setup MSBuild"
        uses: microsoft/setup-msbuild@v1.0.0
                            
      - name: NuGet Restore
        run: nuget restore
      
      - name: Build API
        run: dotnet build -c Release
       
      - name: "Package & Deploy (Beta)"
        run: powershell -File Nuget.ps1
