name: Unit Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Dependencies (Chocolatey)
        run: |
          choco install visualstudio2019
          choco install dotnetcore-sdk
          choco install visualstudio2019-workload-netcorebuildtools

      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Tests
        run: dotnet test
        env:
          steam: ${{ secrets.STEAM_API }}